version: 2.1
jobs:
  build:
    working_directory: ~/tp-javascript
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: test javascript exercices
          command: npm --save install jest && npm test
